### ISSUE TITLE
apiKey is required by observers

### ISSUE THREAD

**Issue by raydaly** [andyfinity/google-map-static#1]
The second use of google-map-static fails. For example, if I change the coordinates I will not get back a new map if I've not specified an API key. In this case the API is undefined and the 'observers' never executes. 

observers: [
            "_computeUrl(lat, lng, sizeX, sizeY, mapType, zoom, fitToMarkers, markerAtCenter, apiKey)"
        ],
"Observers are not invoked until all dependent properties are defined (!== undefined)" 
SEE: https://www.polymer-project.org/1.0/docs/devguide/properties#multi-property-observers

**Comment by andyfinity** [comment]
Well, how about that. That's definitely a bug. I'm in a place where I can't fix it for a few days, but I can see how to fix it and will push a new version ASAP.

This is one of my first plugins, and I'm still learning how all this works. It's good to hear someone is using my code! Sorry for the inconvenience.

**Comment by raydaly** [comment]
Great. Using if for http://ales2go.com

**Comment by andyfinity** [comment]
Sorry for the delay. I just pushed a new version. Give it a shot and see if it works for you. I haven't personally tested it, so if it gives you more trouble, I'd be happy to give it another looking at.

Do consider switching to using an API key, though. You'll actually get analytics that way, and it lets you scale much easier.

**Comment by raydaly** [comment]
Thanks. Will be using it with https://ales2go.com. And with an API key in
production.

On Fri, Jun 3, 2016 at 4:07 PM, andyfinity notifications@github.com wrote:

> Sorry for the delay. I just pushed a new version. Give it a shot and see
> if it works for you. I haven't personally tested it, so if it gives you
> more trouble, I'd be happy to give it another looking at.
> 
> Do consider switching to using an API key, though. You'll actually get
> analytics that way, and it lets you scale much easier.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/andyfinity/google-map-static/issues/1#issuecomment-223681180,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAA5fNggezY0z4ZWybD2WaNfmsBlOyu0ks5qIIl5gaJpZM4Inpay
> .

## 

Sign up for beta of my project http://Reading.email
-- a better inbox for newsletters
